mongo-instance:
  build: ./mongo_image
  ports:
   - "127.0.0.1:27017:27017"
  volumes:
   - ./data/mongo:/data/db
  environment:
   - MONGODB_PASS="boemboem"
gis-fiddle-db:
  build: ./postgis_image
  ports:
   -  "127.0.0.1:5432:5432"
  volumes:
   -  ./data/postgis:/tmp/data
  environment:
   - PGDATA=/tmp/data
node:
  build: ./node_image
  ports:
   - "127.0.0.1:6969:6969"
  links:
   - gis-fiddle-db:postgis
   - mongo-instance:mongo
